### ISSUE TITLE
<web> onPageFinish will not trigger on web platform!

### ISSUE THREAD

**Issue by zprial** [apache/incubator-weex#1450]
## Description
Web onPageFinish will not trigger on web platform!

## Environment
Web

## Broken Example
onPageFinish will not trigger in official example!

[http://dotwe.org/vue/94b9a51438390f5ec461f7fcc93707e8](http://dotwe.org/vue/94b9a51438390f5ec461f7fcc93707e8)

Of course I can use `@load` instaed of `@pageFinish`, but, it's will be better if you can support `@pageFinish` on web platform!

**Comment by imyzf** [comment]
It is because of the browser's same-origin policy.
1. There is a js error `Uncaught ReferenceError: url is not defined` in your demo, I fixed it and you will see another error from `<web>` component: `Blocked a frame with origin "http://dotwe.org" from accessing a cross-origin frame.` Demo: http://dotwe.org/vue/ad4d6d4a11e407cdcb24167c2b9da828
2. I changed your url to same origin of dotwe.org, and it works. Demo: http://dotwe.org/vue/7846a576c0150aa52de6ad2caf283c00
