### ISSUE TITLE
js error like "xxx is undefine" will not call onJSException but just log

### ISSUE THREAD

**Issue by luciozhang** [apache/incubator-weex#1798]
And in the same situation, Android will call onException. Since this kind of error is most likely to happen in an app, I think it will be better to call onJSException. So that we can report the error and find  the error in time.

**Comment by zshshr** [comment]
you means that  just  IOS  has this issue ?

**Comment by Hanks10100** [comment]
That's because js framework wrapped `try catch` to the [callback functions](https://github.com/apache/incubator-weex/blob/0.19.0/runtime/bridge/CallbackManager.js#L65-L70) and [event handlers](https://github.com/apache/incubator-weex/blob/rc-0.20.0/runtime/vdom/Element.js#L485-L496) and console it out. I think it's a good idea to throw the exceptions to native handlers, I'll remove those `try catch` in the next version.
