### ISSUE TITLE
Registered custom component functions may override the framework's own functions

### ISSUE THREAD

**Issue by ts0307** [apache/incubator-weex#1853]
The functions of the components registered by registerComponents are likely to override the functions of Element and Node. These functions are the following in the type Element: 
  'removeEvent',
  'toStyle',
  'appendChild',
  'clear',
  'fireEvent',
  'insertAfter',
  'insertBefore',
  'removeChild',
  'addEvent',
  'setAttr',
  'setAttrs',
  'setClassStyle',
  'setStyle',
  'setStyles',
  'toJSON',
  'toString',

and In type Node is
'destroy'

What causes this? Because the registered custom component in Weex corresponds to the type WeexElement, it inherits from Element, and Element defines some functions that operate Node. These Nodes correspond to native components. If these functions are override, they are originally defined on Element. The called function becomes called directly on the native component.

This will lead us to be familiar with the implementation details of weex, and can't use the above name to name the function of the custom component.

So I recommend that all variable names that may be override by the user be prefixed with "$", as Vue does.

Below is an example:

public class test extends WXComponent  {
   public void appendChild () {
     // override the same name function defined by weex Element'
   },
   public void removeChild () {
     // override the same name function defined by weex Element'
   }
}

registerComponents([{"type": "test", "methods": ["appendChild", "removeChild"]}])

**Comment by ts0307** [comment]
@Hanks10100 I think that if a user-defined component function might override the function defined by the framework itself, the documentation should give a description, and those function names are reserved by the framework and cannot be defined by the user. Otherwise, the user must be familiar with the details of the framework to avoid intercepting the functionality of the framework itself.

**Comment by Hanks10100** [comment]
@ts0307  Thank you for pointing out this question. It's really a perplexing feature of js framework.

As you mentioned, If developer register a `"test"` component with an `appendChild` method. Under the hood, js framework will create a new type of `WeexElement`, and add the new method to its prototype, the pseudo-code is like this:

```js
class WeexElement extends Element {}

// custom methods of the "test" component
WeexElement.prototype.appendChild = function () { /* ... */ }
```

At runtime, the custom `appendChild` method will be called instead of the internal one if it exists. It gives developers more capability to customize components, however, maybe it's too powerful and too hard to master.

After consideration, I think we can solve it in two ways:

1. For those render-related methods, prevented them to be overridden. Such as the `appendChild`, `insertBefore`, and `removeChild`, those methods are integrated and hard to be replaced. I think we can make them immutable to make sure the rendering logic is reliable.
2. For those getter/setter methods, developers can still override it as they wish. Such as the `setAttr`, `setStyles`, and `toJSON`, they are independent methods, it's feasible for developers to override it with their own features.

**Comment by YorkShen** [comment]
It seems like the conversation is inactive. If there is any appending issues here, please discuss in the mailing list, which is the perfect place for this kind of discussion.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
