### ISSUE TITLE
iOS scroller component scrollend event return wrong contentOffset

### ISSUE THREAD

**Issue by y500** [apache/incubator-weex#2050]
## Describe the bug
iOS scroller component scrollend event return wrong contentOffset (0, 0).

## Environment
* Device: iPhone Simulator
* OS: iOS12
* Version 0.18

## Expected behavior
the contentOffset returned in the scrollend event is always (0, 0).

**Comment by wqyfavor** [comment]
This is fixed in 0.19+.
If you still want to use 0.18, please modify this part of code in WXScrollerComponent. There was a bug that "scrollViewDidEndDecelerating:" is invoked without a scrollview. 

![image](https://user-images.githubusercontent.com/113776/51981457-11159200-24ce-11e9-9eb3-75e0b372892f.png)
