### ISSUE TITLE
[Android][iOS][Dev-tool]  video组件支持MP4以外格式的视频吗，支持直接指定播放进度seek吗

### ISSUE THREAD

**Issue by hponiang** [apache/incubator-weex#2128]

**Comment by YorkShen** [comment]
Not supported yet.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).

**Comment by DorisOu** [comment]
Unable to play video with url rtsp,show the details as bellow:
<video class="video" src="rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov" controls="nocontrols" play-status='pause' auto-play='true' v-if="showMusic"></video>

how can I solve this problem？
This issue is very urgent,pls help.thks.

**Comment by YorkShen** [comment]
Again, `video` in Weex is for demo purpose, you should not use it in your production environment.
