### ISSUE TITLE
[Android][iOS][Dev-tool] stream.fetch无法调用https接口 0.16.0

### ISSUE THREAD

**Issue by ChangLCS** [apache/incubator-weex#2162]
在使用stream.fetch模块的时候，有的https接口能调用，如 https://login.gpocn.com/config ，有的无法调用，如 https://tradecenter_api.gpocn.com/config ，具体什么原因，能帮我看一下吗

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> When using the stream.fetch module, some https interfaces can be called, such as https://login.gpocn.com/config, some can't be called, such as https://tradecenter_api.gpocn.com/config, what is the reason? Can you help me see it?

Please follow the issue template on Github and give a demo on [dot.we](http://dotwe.org/vue), which will make life so much easier

**Comment by ChangLCS** [comment]
[http://dotwe.org/vue/a087c2b81d8d083ee4a104265d8e980e](http://dotwe.org/vue/a087c2b81d8d083ee4a104265d8e980e)

```
stream.fetch(
      {
              timeout: 5000,
              method:'GET',
              url: 'https://trade_api.qywgpo.com/config',
              type: 'json',
              headers: {
                Accept: 'application/json, text/plain, */*',
                'Content-Type': 'application/json;charset=UTF-8',
              },
    },(res)=> {
      this.text = res
    })
```

in web ,it is work , but in android, it don't work, such as 

![default](https://user-images.githubusercontent.com/18084468/53396346-2dc6bc00-39df-11e9-84d7-fb852d4960a5.png)

**Comment by YorkShen** [comment]
Try use [weex-toolkit](https://github.com/weexteam/weex-toolkit), you will get all the Android/iOS log.

I have captured the Android log ,which is `java.lang.IllegalArgumentException: Invalid input to toASCII: trade_api.qywgpo.com`, Google search it, you will find the [answer](https://stackoverflow.com/questions/51563859/javax-net-ssl-sslhandshakeexception-java-lang-illegalargumentexception-invalid).

`_` is illegal when using https in Android network library. Try the following approach:
* Use `http` instead of `https`.
* Avoid `_` if you assist on `https`.
