### ISSUE TITLE
[Android][iOS] [iOS] weex vue, this.$refs.xxx.ref, normal div is normal, but the div in components returns undefined

### ISSUE THREAD

**Issue by hardui** [apache/incubator-weex#2228]
example:
http://dotwe.org/vue/c49eded544dcd35726296942e9a2081c

when use Weex playground app and click the button, we can see demo1 this.$refs.xxx.ref is undefined.but demo2 have

**Comment by YorkShen** [comment]
I think this issue is about front-end, please have a look @Hanks10100 , thanks

**Comment by Hanks10100** [comment]
**It's an expected behavior.** Please refer to the official document of the `ref` attribute: https://vuejs.org/v2/api/#ref

> The reference will be registered under the parent component’s $refs object. If used on a plain DOM element, the reference will be that element; if used on a child component, the reference will be component instance.

The value of `this.$refs.xxx` depends where the `ref="xxx"` is.

The `ref="demotwo"` is used on the weex element, so it contains the `this.$refs.demotwo.ref`.But the `ref="demo"` is used on the custom component of Vue, so the result of `this.$refs.demo` is a Vue component, not a weex element, it doesn't contains the `this.$refs.demo.ref` property.

**Comment by Hanks10100** [comment]
By the way, the `this.$refs.xxx` could be Vue component, DOM element, Weex element, or an array of them, according to where you are using it. Moreover it could be changed at rendering time. In short, **it's platform sensitive and dynamic.** So always check the value before using it.
