### ISSUE TITLE
[Android]weex的nativie库不支持64位

### ISSUE THREAD

**Issue by hanzhida** [apache/incubator-weex#2267]
之前已经有一个[issue](https://github.com/apache/incubator-weex/issues/2140)，但是被close了。[这个政策](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html)是google强制要求的，2019/08/01开始，每个32位对应的native so库必须有相应的64位，否则无法发布更新

> All new apps and app updates that include native code are required to provide 64-bit versions in addition to 32-bit versions when publishing to Google Play

鉴于时间紧迫，64位支持已经不是一个feature，而是一个未来影响开发者使用的bug了，主要是会在海外开展业务，googleplay发布的app。希望能尽快提供64位的native库

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: There was already an issue before, but it was closed. This policy is google mandatory, starting at 2019/08/01, each 32-bit native so library must have a corresponding 64-bit, otherwise it is not possible to release updates All new apps and app updates that include native code are required to provide 64 -bit versions in addition to 32-bit versions when publishing to Google Play Given the time constraints, 64-bit support is no longer a feature, but a bug that will affect developers in the future, mainly to conduct business overseas, googleplay released App. I hope to provide a 64-bit native library as soon as possible.

Please subscribe [weex mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list) where this issue is already discussed.

FYI: As 64 bit support is in early stage, I can't give you a specified schedule yet. What I can tell you is that we will launch 64 bit support before 1st, August, 2019. Please subscribe [weex mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list), we will announce such features in mailing list. Github issue is only for bug report.

**Comment by hanzhida** [comment]
got it. thanks for the  feedback
