### ISSUE TITLE
[Android] 6.17-6.18的代码更新导致编译失败

### ISSUE THREAD

**Issue by chaopei1989** [apache/incubator-weex#2579]
## Describe the bug
6.17号之前的版本是可以编译成功的, 6.19号早上更新后编译失败, 信息如下:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':playground:mergeDexDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6m 17s
123 actionable tasks: 66 executed, 57 up-to-date

编译环境 window10, ndk-r16

**Comment by YorkShen** [comment]
In order to obey [Google's 64 bit supporting rule](https://developer.android.com/distribute/best-practices/develop/64-bit), Weex update NDK 16 to 18.

Please upgrade to ndk 18 or higher, thanks. I will update the document soon.

Feel free to reopen this issue if you have further questions. *I only response to issues that are open.*
