### ISSUE TITLE
[iOS] Error installing WeexSDK version 0.20.1

### ISSUE THREAD

**Issue by sapphirezzz** [apache/incubator-weex#2601]
pod install 时出现以下错误：

[!] Error installing WeexSDK
[!] /usr/local/bin/git clone https://github.com/apache/incubator-weex.git /var/folders/zg/0xpvbnx13dg7hbdh5022h3tw0000gn/T/d20190624-40786-1vzvpb --template= --single-branch --depth 1 --branch 0.20.1

Cloning into '/var/folders/zg/0xpvbnx13dg7hbdh5022h3tw0000gn/T/d20190624-40786-1vzvpb'...
warning: Could not find remote branch 0.20.1 to clone.
fatal: Remote branch 0.20.1 not found in upstream origin

**Comment by paryace** [comment]
github上，0.20.1的tag已经没了

**Comment by sapphirezzz** [comment]
> github上，0.20.1的tag已经没了

嗯的，就是希望他们误删的话能加回来，毕竟一直用这个版本，现在强制让升级版本不合理。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: When is the waterfall version, I can't show the style of the waterfall here?

Let me explain the reason here. Weex is under ASF (Apache Software Foundation), and the Weex community has to follow the rule of ASF, which is every release/tag must be voted before published. As 0.20.1 is never voted in the community, we have to delete the tag.

You can choose `0.20.0`, which is voted and still on Github repo.

If you have other questions, you could ask in the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list)

IMO, I don't think ASF will change the rule of release procedure.
