### ISSUE TITLE
[iOS]js调用native module方法，在native中刷新UI无效（是主线程）

### ISSUE THREAD

**Issue by imwangxuesen** [apache/incubator-weex#2618]
## Describe the bug

js调用Native Module的方法，在Native 方法中获取主线程并刷新UI 无效

## Environment

`
Native Module:
WX_EXPORT_METHOD(@selector(didScrollToIndex:))
- (void)didScrollToIndex:(NSInteger)index {
      dispatch_async(dispatch_get_main_queue(), ^{
         刷新Native UI... 无效
      }
}

也尝试了
- (NSThread *)targetExecuteThread {
    return [NSThread mainThread];
}
`
是我的代码写的有问题吗？如何解决

**Comment by imwangxuesen** [comment]
已解决，这个native页面也是module，回调时，weex会创建一个新的module实例，所以，在被调用方法中拿原来页面中的UI是拿不到的，因为不是一个实例。
解决方案：
1，用通知告诉原页面
2，通过类单例的方式获取到原页面实例

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: [iOS]js calls native module method, refreshing UI in native is invalid (is the main thread)

It seems the issue is solved, I will just close it.

*If you could describe your question in English, it would save a lot of time for developers to search github issue. As they do not need to search English and Chinese twice.*
