### ISSUE TITLE
[Android] Native can`t print “console log” to java where weex version is 0.26(java)

### ISSUE THREAD

**Issue by Miste-won** [apache/incubator-weex#2668]
JS 使用 console.log()打印日志时，native层有调用WeexConsoleBinding::printLog()方法，但是执行WeexCore::PrintLog时,代码块：LogBridge* logBridge = WeexCore::WeexCoreManager::Instance()->get_log_bridge();变量logBridge在其进程中不能够获取到实例引用；WeexCoreManager在运行内存中有2个内存引用，看了下weex_js_connnection.cpp是有fork()子进程的，但是console log不能正常输出到java ,而WeexCore render 相关的正常输出；

**Comment by st-dc** [comment]
I also have this problem! I don't know how to repair it.

**Comment by YorkShen** [comment]
As there is no JNI environment in subprocess, the C++ -> JAVA message channel will not work without IPC.

However, you can just print log by `console.error` or`console.warn`, `console.info` instead of `console.log` in weex 0.26

We shall make IPC chanel in next version to make `console.log` work as expected.

**Comment by shenhuniurou** [comment]
> As there is no JNI environment in subprocess, the C++ -> JAVA message channel will not work without IPC.
> 
> However, you can just print log by `console.error` or`console.warn`, `console.info` instead of `console.log` in weex 0.26
> 
> We shall make IPC chanel in next version to make `console.log` work as expected.

But `console.error`  `console.warn`  `console.info` all doesn't work in weex 0.26 now

**Comment by dufangyu1990** [comment]
请问console.debug/info/error日志现在原生WxLogUtils接收不到了，这个要怎么弄。。
