### ISSUE TITLE
0.20版本windows打包和mac打包发现apk大小不一致！大佬们什么原因

### ISSUE THREAD

**Issue by KaelInvoker** [apache/incubator-weex#2852]
![image](https://user-images.githubusercontent.com/37531571/63745959-1f962180-c8d6-11e9-8d56-189251d58eb0.png)

![image](https://user-images.githubusercontent.com/37531571/63745948-1311c900-c8d6-11e9-895c-64721a418fe9.png)

同样的打包配置，我本地是windows本。服务器是mac本，用gradle assembleRelease命令打包，发现服务器打的apk包里的so库大小比windows大很多。哪位大佬知道？最初我以为是AS3.0自动压缩so导致，当我本地配置了不压缩后，重新打包还是和之前的大小一样大。
 packagingOptions{
       doNotStrip "*/armeabi-v7a/*.so"
    }
另外，我发现自己本地打包时，下面的两个目录的so库大小也不一直。
![image](https://user-images.githubusercontent.com/37531571/63745849-cded9700-c8d5-11e9-980b-54f8e1b095f0.png)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: 0.20 version of windows packaging and mac packaging found apk size is inconsistent! What are the reasons for us?

I can't tell you what happened exactly as I am not a committer of NDK, but generally speaking, this problem is caused by stripping. As you can see, the size of many shared libraries are different, not only Weex. Change `/armeabi-v7a/.so` to `/armeabi-v7a/*.so` will give you what you want.
