### ISSUE TITLE
64bit support for x86 arch

### ISSUE THREAD

**Issue by dim0xff** [apache/incubator-weex#2886]
Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures.
But there are still no x86_64 support.

Do you have any plans to add it?

**Comment by YorkShen** [comment]
Currently, I can't give you a timeline about supporting `x86-64` as most of users run Apps with `armv8-64` phone instead of `x86-64`.

The main problem here is compiling [JSC](https://github.com/alibaba/weex_js_engine/tree/bridge_branch_mergeTimer) (a dependency of Weex) for x86-64 ABI. So far, no progress. You're welcomed to help us solve the problem.
