### ISSUE TITLE
Any reason for READ_PHONE_STATE permission?

### ISSUE THREAD

**Issue by dim0xff** [apache/incubator-weex#2890]
Why READ_PHONE_STATE permission is there? It appears after https://github.com/apache/incubator-weex/pull/2776 merging

https://github.com/apache/incubator-weex/blob/6daad9ee33ebd50dba2e01bd3a972b3488ba56ac/android/sdk/src/main/AndroidManifest.xml#L22

**Comment by YorkShen** [comment]
Get IMEI of user's phone.

As you might observed, `WXEnvironment.getDevId()` is always be invoked no matter you specify `android:name="android.permission.READ_PHONE_STATE`  or not since very early version of Weex. In some phone, calling `getSystemService(Context.TELEPHONY_SERVICE)).getDeviceId()` in code without corresponding `AndroidManifest` will cause crash. I just updated the Manifest to prevent possible crash.

https://github.com/apache/incubator-weex/blob/24a30b31e759343668cfe6b8f3de264dd3f586fe/android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java#L404-L405
